import router from '@adonisjs/core/services/router'

router.post('/pacientes', '#controllers/PacientesController.create')
router.get('/pacientes', '#controllers/PacientesController.readAll')
router.get('/pacientes/titular', '#controllers/PacientesController.readByITitular')
router.get('/pacientes/beneficiarios', '#controllers/PacientesController.readBeneficiarios')
router.get('/pacientes/mi-perfil', '#controllers/.PacientesController.readByUsuarioLogueado')
router.get('/pacientes/por-usuario/:usuario_id', '#controllers/PacientesController.readByUsuarioId')
router.get('/pacientes/:id', '#controllers/PacientesController.readById')
router.delete('/pacientes/:id', '#controllers/PacientesController.deleteById')
router.put('/pacientes/:id', '#controllers/PacientesController.updateById')
router.post('/createBeneficiario', 'PacientesController, createBeneficiario')
router.put('/updateBeneficiario/:id', 'PacientesController, updateBeneficiario')
router.delete('/deleteBeneficiario/:id', 'PacientesController, deleteBeneficiario')
router.get('/beneficiarios/:id', 'PacientesController, readBeneficiarioById')
